apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # ---------------------------
      # 1️⃣ INIT CONTAINER (BROKEN)
      # ---------------------------
      initContainers:
      - name: wait-for-backend
        image: curlimages/curl:7.87.0
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "[1] Checking DNS connectivity..."
            if ! nslookup google.com; then
              echo "DNS check failed: cannot resolve google.com"
              exit 1
            fi

            echo "[2] DNS OK. Checking backend URL connectivity..."

            if ! curl -f --max-time 2 http://backend-svc-wrong.default.svc.cluster.local; then
              echo "Backend URL check failed (doesn't exist or incorrect name)."
              exit 1
            fi

            echo "[3] Backend reachable. Init complete."
      # ---------------------------
      # 2️⃣ MAIN CONTAINER (OOM)
      # ---------------------------

      containers:
      - name: frontend
        image: busybox
        command: ["sh", "-c"]
        args:
          - |
            echo "Starting controlled memory eater..."

            TARGET_MB=${TARGET_MB:-50}   # Total memory needed
            STEP_MB=${STEP_MB:-5}        # Allocate per iteration
            SLEEP=${SLEEP:-1}            # Delay between allocations

            i=0
            data=""

            while [ $i -lt $TARGET_MB ]; do
              chunk=$(dd if=/dev/zero bs=1M count=$STEP_MB 2>/dev/null)
              data="$data$chunk"
              i=$((i + STEP_MB))
              echo "Allocated ${i}MB / ${TARGET_MB}MB"
              sleep $SLEEP
            done

            echo "Finished allocating memory. Sleeping..."
            sleep infinity
        resources:
          requests:
            memory: "20Mi"   # Low Request
          limits:
            memory: "30Mi"  # Low Limit
        env:
        - name: BACKEND_URL
          value: "http://backend-svc-wrong.default.svc.cluster.local"  # WRONG
        - name: TARGET_MB
          value: "50"
        - name: STEP_MB
          value: "5"
        - name: SLEEP
          value: "1"
